blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Garrett12123/algo1/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/Garrett12123/algo1/blob/main/README.md
    about: Read the project documentation and setup instructions 